services:
  webserver:
    image: nginx:latest
    container_name: nginx-production
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: always
